# https://github.com/maxpou/docker-symfony/blob/master/docker-compose.yml
version: '3.2'

services:
    
    database:
      image: postgres
      working_dir: /srv
      volumes:
        - database:/usr/local/var/postgres
      ports:
        - "127.0.0.1:8432:5432"
      networks:
        - open_nedeleg
      environment:
        - POSTGRES_PASSWORD=open_nedeleg
        - POSTGRES_DB=open_nedeleg

    php:
        build:
            context: docker/php
        working_dir: /srv
        volumes:
            - ./:/srv/
        networks:
          - open_nedeleg

    nginx:
        image: nginx:1-alpine
        volumes:
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/srv/:ro
        ports:
            - "8000:80"
        networks:
          - open_nedeleg

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
            - "1025:1025"
        networks:
          - open_nedeleg

volumes:
    database: ~

networks:
    open_nedeleg: ~